### ISSUE TITLE
should not use "latest" in singularity

### ISSUE THREAD

**Issue by soichih** [brainlife/app-freesurfer-stats#1]
This App is using "latest" tag for the singularity container

```
singularity exec docker://brainlife/freesurfer-stats:latest
```

We should not use `latest` (or not tag) for any container we run as we won't be able to ensure that we always run the same container. Please set a tag for the current `latest` container and use that tag instead.

**Comment by bacaron** [comment]
I updated the docker container with a tag 1.2 and updated the singularity calls to point to that.
